---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/properties":
    post:
      summary: create property
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                property_address:
                  type: string
                property_type:
                  type: string
                number_of_bathrooms:
                  type: integer
                number_of_bedrooms:
                  type: integer
                number_of_sitting_rooms:
                  type: integer
                number_of_toilets:
                  type: integer
                number_of_kitchens:
                  type: integer
                property_owner:
                  type: string
                description:
                  type: string
                valid_from:
                  type: string
                  format: date
                valid_to:
                  type: string
                  format: date
              required:
              - property_address
              - property_type
              - valid_from
              - valid_to
              - description
              - property_owner
              - number_of_kitchens
              - number_of_toilets
              - number_of_bathrooms
              - number_of_bedrooms
              - number_of_sitting_rooms
    get:
      summary: find_all property
      responses:
        '200':
          description: successful
  "/properties/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: find_by_id property
      responses:
        '200':
          description: successful
    put:
      summary: update property
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number_of_bathrooms:
                  type: integer
                number_of_bedrooms:
                  type: integer
                number_of_sitting_rooms:
                  type: integer
                number_of_toilets:
                  type: integer
                number_of_kitchens:
                  type: integer
                description:
                  type: string
                valid_from:
                  type: string
                  format: date
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
