# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  port: 9091
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lekki_property_api_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: lekki_property_api_test
  username: postgres
  password: password
  host: localhost
  port: 5434

production:
  <<: *default
  database: lekki_property_api_production
  username: lekki_property_api
  password: <%= ENV["LEKKI_PROPERTY_API_DATABASE_PASSWORD"] %>
